name: Init Infrastructure  
 
on: 
  pull_request:
    branches: [ master ]
    types: [ closed ]
    paths: 
      - ".github/workflows/01_init_terraform_infra.yml" 

jobs:

  terraform_infra:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true 
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      TF_VAR_SSH_KEY: ${{secrets.TF_VAR_SSH_KEY}}
      
    steps:
      - uses: actions/checkout@v2 

      - name: "Login Azure ClI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PROJECTIN_SP }}

      - name: "Login AKS"
        uses: azure/aks-set-context@v1
        env:
          CREDENTIALS: ${{ secrets.ACR_AKS_CREDENTIALS }} 
        with:
          creds: ${{ env.CREDENTIALS }} # Azure credentials
          resource-group: 'rg-hipster-dev-eastus'
          cluster-name: 'aks-hipster-dev-eastus'

      - name: 'Login Azure ACR'
        uses: azure/docker-login@v1
        with:
            login-server: ${{ secrets.ACR_SERVER }}
            username: ${{ secrets.ACR_USER }}
            password: ${{ secrets.ACR_PASS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd 01_Terraform_IaC
          terraform init
        continue-on-error: true

      - name: Terraform plan
        run: |
          cd 01_Terraform_IaC
          terraform plan
        continue-on-error: true

      - name: Terraform apply
        run: |
          cd 01_Terraform_IaC
          terraform apply --auto-approve
        continue-on-error: true

  acr_to_aks:
    runs-on: ubuntu-latest 
    needs: terraform_infra 
    steps:

      - uses: actions/checkout@v2

      - name: Login to AKS
        uses: azure/aks-set-context@v1
        env:
          CREDENTIALS: ${{ secrets.ACR_AKS_CREDENTIALS }}
        with:
          creds: ${{ env.CREDENTIALS }}
          resource-group: rg-hipster-dev-eastus
          cluster-name: aks-hipster-dev-eastus
      
      - name: "Login to Azure CLI" 
        run: |
          az login -u ricardo.mora@digitalonus.com -p DreamTeam1

      - name: Attaching Cluster
        run: | 
          az aks update -n aks-hipster-dev-eastus -g rg-hipster-dev-eastus --attach-acr hipsterequipofive1 

      - name: Checking the ACR
        run: |
          az aks check-acr -g rg-hipster-dev-eastus -n aks-hipster-dev-eastus  --acr ${{ secrets.ACR_SERVER }}