name: Checkoutservice Image 

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
    paths: 
      - "02_Application/src/checkoutservice/*"

jobs:

  build:

    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Login Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}
        
    - name: Login Azure ACR
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}
    
    - name: Deleted Img in ACR
      run: |
          az acr repository delete --name hipsterequipofive1 --image checkoutservice:latest -y

    - name: Build the Docker images
      run: |
           docker build 02_Application/src/checkoutservice/. --tag ${{ secrets.ACR_SERVER }}/checkoutservice:latest
           docker push ${{ secrets.ACR_SERVER }}/checkoutservice:latest

  uploading_acr:

    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: "Login Azure ClI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}

    - name: "Login AKS"
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }} # Azure credentials
        resource-group: 'rg-hipster-dev-eastus'
        cluster-name: 'aks-hipster-dev-eastus' 
      id: login   
    
    - name: 'Install helm'
      uses: azure/setup-helm@v1
      with:
        version: latest # default is latest stable

    - name: Install Kubectl 
      uses: azure/setup-kubectl@v1  
      with:
        version: latest # default is latest stable
      id: install

    - name: Update New checkoutservice
      run: |
           kubectl set image deployment/checkoutservice server=${{ secrets.ACR_SERVER }}/checkoutservice:latest 
          
      
