name: Recommendationservice Image 

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
    paths: 
      - "04_Testing_CI/recommendationservice/*"

jobs:

  build:

    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Login Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}
        
    - name: Login Azure ACR
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}

    - name: Build the Docker images
      run: |
           docker build 04_Testing_CI/recommendationservice/. --tag ${{ secrets.ACR_SERVER }}/recommendationservice:latest

  test:

    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash