
# File: .github/workflows/workflow.yml

on: [push]

name: prtojectIn

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.PROJECTIN_SP }}
        login-server: hipstershopimg.azurecr.io
    
    - run: |
        az acr build  --registry HipstershopImg --image adservergit:v1 projectIn/src/adservice/

